import axios from 'axios';

const accessories = [
  {
    id: 1,
    type: 'bag',
    colors: ['black', 'brown', 'tan'],
    gender: 'women',
    description: 'A stylish leather bag for women.',
  },
  {
    id: 2,
    type: 'wallet',
    colors: ['brown', 'blue', 'red'],
    gender: 'men',
    description: 'A sleek leather wallet for men.',
  },
  {
    id: 3,
    type: 'belt',
    colors: ['black', 'brown', 'grey'],
    gender: 'women',
    description: 'A classic leather belt for women.',
  },
  {
    id: 4,
    type: 'bag',
    colors: ['red', 'green', 'blue'],
    gender: 'men',
    description: 'A versatile leather bag for men.',
  },
  {
    id: 5,
    type: 'wallet',
    colors: ['black', 'brown', 'grey'],
    gender: 'women',
    description: 'A practical leather wallet for women.',
  },
  {
    id: 6,
    type: 'belt',
    colors: ['black', 'brown', 'blue'],
    gender: 'men',
    description: 'A stylish leather belt for men.',
  },
  {
    id: 7,
    type: 'bag',
    colors: ['brown', 'tan', 'grey'],
    gender: 'women',
    description: 'A spacious leather bag for women.',
  },
  {
    id: 8,
    type: 'wallet',
    colors: ['black', 'blue', 'tan'],
    gender: 'men',
    description: 'A durable leather wallet for men.',
  },
  {
    id: 9,
    type: 'belt',
    colors: ['brown', 'black', 'red'],
    gender: 'women',
    description: 'A fashionable leather belt for women.',
  },
  {
    id: 10,
    type: 'bag',
    colors: ['blue', 'red', 'tan'],
    gender: 'men',
    description: 'A rugged leather bag for men.',
  },
  {
    id: 11,
    type: 'wallet',
    colors: ['brown', 'grey', 'red'],
    gender: 'women',
    description: 'A chic leather wallet for women.',
  },
  {
    id: 12,
    type: 'belt',
    colors: ['black', 'brown', 'green'],
    gender: 'men',
    description: 'A versatile leather belt for men.',
  },
  {
    id: 13,
    type: 'bag',
    colors: ['brown', 'black', 'blue'],
    gender: 'women',
    description: 'A stylish leather bag for women.',
  },
  {
    id: 14,
    type: 'wallet',
    colors: ['black', 'blue', 'green'],
    gender: 'men',
    description: 'A functional leather wallet for men.',
  },
  {
    id: 15,
    type: 'belt',
    colors: ['brown', 'tan', 'blue'],
    gender: 'women',
    description: 'A trendy leather belt for women.',
  },
  {
    id: 16,
    type: 'bag',
    colors: ['black', 'grey', 'green'],
    gender: 'men',
    description: 'A practical leather bag for men.',
  },
  {
    id: 17,
    type: 'wallet',
    colors: ['brown', 'blue', 'tan'],
    gender: 'women',
    description: 'A sleek leather wallet for women.',
  },
  {
    id: 18,
    type: 'belt',
    colors: ['black', 'brown', 'red'],
    gender: 'men',
    description: 'A durable leather belt for men.',
  },
  {
    id: 19,
    type: 'bag',
    colors: ['blue', 'tan', 'red'],
    gender: 'women',
    description: 'A stylish leather bag for women.',
  },
  {
    id: 20,
    type: 'wallet',
    colors: ['black', 'grey', 'green'],
    gender: 'men',
    description: 'A functional leather wallet for men.',
  },
  {
    id: 21,
    type: 'belt',
    colors: ['brown', 'black', 'blue'],
    gender: 'women',
    description: 'A versatile leather belt for women.',
  },
  {
    id: 22,
    type: 'bag',
    colors: ['black', 'brown', 'green'],
    gender: 'men',
    description: 'A durable leather bag for men.',
  },
  {
    id: 23,
    type: 'wallet',
    colors: ['brown', 'blue', 'tan'],
    gender: 'women',
    description: 'A sleek leather wallet for women.',
  },
  {
    id: 24,
    type: 'belt',
    colors: ['black', 'red', 'grey'],
    gender: 'men',
    description: 'A stylish leather belt for men.',
  },
  {
    id: 25,
    type: 'bag',
    colors: ['brown', 'blue', 'red'],
    gender: 'women',
    description: 'A trendy leather bag for women.',
  },
  {
    id: 26,
    type: 'wallet',
    colors: ['black', 'blue', 'green'],
    gender: 'men',
    description: 'A functional leather wallet for men.',
  },
  {
    id: 27,
    type: 'belt',
    colors: ['brown', 'black', 'tan'],
    gender: 'women',
    description: 'A versatile leather belt for women.',
  },
  {
    id: 28,
    type: 'bag',
    colors: ['black', 'brown', 'grey'],
    gender: 'men',
    description: 'A practical leather bag for men.',
  },
  {
    id: 29,
    type: 'wallet',
    colors: ['brown', 'blue', 'red'],
    gender: 'women',
    description: 'A chic leather wallet for women.',
  },
  {
    id: 30,
    type: 'belt',
    colors: ['black', 'tan', 'green'],
    gender: 'men',
    description: 'A stylish leather belt for men.',
  },
];

export const getProducts = () => {
  return accessories;
};
